"""Before/after sample set (issue 08): the same fixed FableSpecs generated by
the Base Model and the Aligned Model, side by side — the RLHF effect made
visible, and the acceptance-criterion artifact for issue 08. Same seed per
spec on both sides: same sampling noise, different weights."""

from __future__ import annotations

import itertools
import json
from dataclasses import asdict
from pathlib import Path
from statistics import mean

import torch
from tokenizers import Tokenizer

from tinyfables.config import SamplesConfig
from tinyfables.data import iter_rows
from tinyfables.generate import generate_fable
from tinyfables.model import GPT
from tinyfables.paraphrases import parse_canonical_prompt
from tinyfables.prompts import FableSpec, render_canonical_prompt
from tinyfables.stage import write_manifest

_ELEMENTS = ("character", "setting", "challenge", "outcome", "moral")


def _resolve_device(name: str) -> str:
    if name != "auto":
        return name
    if torch.cuda.is_available():
        return "cuda"
    if torch.backends.mps.is_available():
        return "mps"
    return "cpu"


def _spec_from_prompt(prompt: str) -> FableSpec | None:
    parsed = parse_canonical_prompt(prompt)
    if parsed is None:
        return None
    return FableSpec(
        **{field: getattr(parsed, field) for field in _ELEMENTS},
        age_range=parsed.age_range,
        word_count=parsed.word_count,
    )


def run(cfg: SamplesConfig, out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    specs: list[FableSpec] = []
    for row in itertools.islice(iter_rows(cfg.source, cfg.seed), cfg.n_specs * 4):
        spec = _spec_from_prompt(row["prompt"])
        if spec is not None:
            specs.append(spec)
        if len(specs) >= cfg.n_specs:
            break
    if len(specs) < cfg.n_specs:
        raise ValueError(
            f"samples requested {cfg.n_specs} specs but only found {len(specs)} canonical prompts in {cfg.source}"
        )

    device = _resolve_device(cfg.device)
    tok = Tokenizer.from_file(str(Path(cfg.tokenizer_dir) / "tokenizer.json"))
    base = GPT.from_pretrained(cfg.base_checkpoint).to(device).eval()
    aligned = GPT.from_pretrained(cfg.aligned_checkpoint).to(device).eval()

    def _gen(model, prompt_text: str, seed: int) -> str:
        return generate_fable(
            model,
            tok,
            prompt_text,
            max_new_tokens=cfg.max_new_tokens,
            min_new_tokens=cfg.min_new_tokens,
            do_sample=True,
            temperature=cfg.temperature,
            top_k=cfg.top_k,
            seed=seed,
            device=device,
        )

    rows = []
    for i, spec in enumerate(specs):
        prompt = render_canonical_prompt(spec)
        base_fable = _gen(base, prompt, cfg.seed + i)
        aligned_fable = _gen(aligned, prompt, cfg.seed + i)
        rows.append(
            {
                "spec_id": f"spec-{i:03d}",
                "spec": asdict(spec),
                "prompt": prompt,
                "base": base_fable,
                "aligned": aligned_fable,
                "base_words": len(base_fable.split()),
                "aligned_words": len(aligned_fable.split()),
            }
        )

    samples_path = out_dir / "samples.jsonl"
    samples_path.write_text("".join(json.dumps(row) + "\n" for row in rows))

    report_lines = ["# Before/after generations (Base vs Aligned)", ""]
    for row in rows:
        report_lines += [
            f"## {row['spec_id']}",
            "",
            f"- character: {row['spec']['character']} · setting: {row['spec']['setting']}",
            f"- challenge: {row['spec']['challenge']} · outcome: {row['spec']['outcome']}",
            f"- moral: {row['spec']['moral']}",
            "",
            f"**Base** ({row['base_words']} words):",
            "",
            "```",
            row["base"],
            "```",
            "",
            f"**Aligned** ({row['aligned_words']} words):",
            "",
            "```",
            row["aligned"],
            "```",
            "",
        ]
    report_path = out_dir / "samples_report.md"
    report_path.write_text("\n".join(report_lines))

    summary = {
        "n_specs": len(rows),
        "base_mean_words": mean(r["base_words"] for r in rows),
        "aligned_mean_words": mean(r["aligned_words"] for r in rows),
        "temperature": cfg.temperature,
        "seed": cfg.seed,
    }
    summary_path = out_dir / "samples_summary.json"
    summary_path.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")

    write_manifest(
        out_dir,
        "samples",
        cfg,
        [samples_path, report_path, summary_path],
        inputs={
            "base_model.safetensors": Path(cfg.base_checkpoint) / "model.safetensors",
            "aligned_model.safetensors": Path(cfg.aligned_checkpoint) / "model.safetensors",
            "tokenizer.json": Path(cfg.tokenizer_dir) / "tokenizer.json",
        },
    )
