"""Render eval metrics into a Markdown report.

Torch-free human output only; the machine-readable source of truth stays in the
metrics JSON and manifest files generated by the eval pipeline.
"""

from __future__ import annotations

from pathlib import Path

_FAMILY_ORDER = ("canonical", "seen-template", "held-out-template")


def _fmt_float(value: float) -> str:
    return f"{value:.3f}"


def write_eval_report(out_dir, metrics) -> Path:
    out_path = Path(out_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    perplexity = metrics["perplexity"]
    generation = metrics["generation"]
    grid = metrics["adherence_grid"]
    provenance = metrics["provenance"]

    lines = [
        "# Eval report",
        "",
        f"**Fable-token perplexity:** {_fmt_float(perplexity['perplexity'])} "
        f"(loss {_fmt_float(perplexity['fable_token_loss'])}, {perplexity['n_rows']} rows)",
        "",
        "## Generation quality",
        "",
        "| metric | value |",
        "|---|---|",
        f"| specs | {generation['n_specs']} |",
        f"| distinct-1 | {_fmt_float(generation['distinct_1'])} |",
        f"| distinct-2 | {_fmt_float(generation['distinct_2'])} |",
        f"| repetition-4 | {_fmt_float(generation['repetition_4'])} |",
        f"| length mean/median | {generation['length']['mean']}/{generation['length']['median']} |",
        f"| length min/max | {generation['length']['min']}/{generation['length']['max']} |",
        f"| moral delivery | {_fmt_float(generation['moral_delivery_rate'])} "
        f"(thr {_fmt_float(generation['moral_threshold'])}) |",
        "",
        "## Adherence grid",
        "",
        "| family | character | setting | challenge | outcome | overall | moral | n |",
        "|---|---|---|---|---|---|---|---|",
    ]

    for family in _FAMILY_ORDER:
        if family not in grid:
            continue
        row = grid[family]
        lines.append(
            f"| {family} | {row['character']:.3f} | {row['setting']:.3f} | "
            f"{row['challenge']:.3f} | {row['outcome']:.3f} | {row['overall']:.3f} | "
            f"{row['moral_delivery']:.3f} | {row['n']} |"
        )

    lines.extend(
        [
            "",
            "## Provenance",
            f"- checkpoint: `{provenance['checkpoint_sha']}`",
            f"- tokenizer: `{provenance['tokenizer_sha']}`",
            f"- seed: {provenance['seed']}",
            f"- versions: {provenance['versions']}",
            "",
        ]
    )

    report_path = out_path / "eval_report.md"
    report_path.write_text("\n".join(lines))
    return report_path
